// Mirrors the rows seeded in supabase/migrations/20260101000010_seed_permissions.sql.
// Keeping these as named constants (rather than sprinkling raw strings
// through the app) means a typo becomes a compile error instead of a
// silently-denied action.
export const PERMISSIONS = {
  IT_TICKETS_VIEW: "IT.TICKETS.VIEW",
  IT_TICKETS_CREATE: "IT.TICKETS.CREATE",
  IT_TICKETS_UPDATE: "IT.TICKETS.UPDATE",
  IT_TICKETS_DELETE: "IT.TICKETS.DELETE",
  IT_TICKETS_ASSIGN: "IT.TICKETS.ASSIGN",
  IT_TICKETS_COMMENT: "IT.TICKETS.COMMENT",
  IT_TICKETS_RESOLVE: "IT.TICKETS.RESOLVE",
  IT_TICKETS_CLOSE: "IT.TICKETS.CLOSE",

  ADMIN_USERS_VIEW: "ADMIN.USERS.VIEW",
  ADMIN_USERS_MANAGE: "ADMIN.USERS.MANAGE",
  ADMIN_ROLES_MANAGE: "ADMIN.ROLES.MANAGE",
  ADMIN_DEPARTMENTS_MANAGE: "ADMIN.DEPARTMENTS.MANAGE",
  ADMIN_IT_CATEGORIES_MANAGE: "ADMIN.IT_CATEGORIES.MANAGE",
  ADMIN_COMPANY_SETTINGS_MANAGE: "ADMIN.COMPANY_SETTINGS.MANAGE",
  ADMIN_AUDIT_VIEW: "ADMIN.AUDIT.VIEW",

  IT_INVENTORY_VIEW: "IT.INVENTORY.VIEW",
  IT_INVENTORY_CREATE: "IT.INVENTORY.CREATE",
  IT_INVENTORY_UPDATE: "IT.INVENTORY.UPDATE",
  IT_INVENTORY_DELETE: "IT.INVENTORY.DELETE",
  IT_INVENTORY_ASSIGN: "IT.INVENTORY.ASSIGN",
  IT_INVENTORY_DISPOSE: "IT.INVENTORY.DISPOSE",
  IT_INVENTORY_REPAIR: "IT.INVENTORY.REPAIR",
  IT_INVENTORY_EXPORT: "IT.INVENTORY.EXPORT",
  IT_INVENTORY_PRINT: "IT.INVENTORY.PRINT",

  IT_CREDENTIALS_VIEW: "IT.CREDENTIALS.VIEW",
  IT_CREDENTIALS_CREATE: "IT.CREDENTIALS.CREATE",
  IT_CREDENTIALS_UPDATE: "IT.CREDENTIALS.UPDATE",
  IT_CREDENTIALS_DELETE: "IT.CREDENTIALS.DELETE",
  IT_CREDENTIALS_REVEAL: "IT.CREDENTIALS.REVEAL",

  IT_IP_VIEW: "IT.IP.VIEW",
  IT_IP_UPDATE: "IT.IP.UPDATE",
  IT_IP_MANAGE: "IT.IP.MANAGE",

  IT_NOTIFICATIONS_VIEW: "IT.NOTIFICATIONS.VIEW",
  IT_NOTIFICATIONS_MANAGE: "IT.NOTIFICATIONS.MANAGE",

  IT_BUDGET_VIEW: "IT.BUDGET.VIEW",
  IT_BUDGET_CREATE: "IT.BUDGET.CREATE",
  IT_BUDGET_UPDATE: "IT.BUDGET.UPDATE",
  IT_BUDGET_DELETE: "IT.BUDGET.DELETE",
  IT_BUDGET_APPROVE: "IT.BUDGET.APPROVE",
  IT_BUDGET_CLOSE: "IT.BUDGET.CLOSE",

  IT_PROCUREMENT_VIEW: "IT.PROCUREMENT.VIEW",
  IT_PROCUREMENT_CREATE: "IT.PROCUREMENT.CREATE",
  IT_PROCUREMENT_UPDATE: "IT.PROCUREMENT.UPDATE",
  IT_PROCUREMENT_DELETE: "IT.PROCUREMENT.DELETE",
  IT_PROCUREMENT_SUBMIT: "IT.PROCUREMENT.SUBMIT",
  IT_PROCUREMENT_APPROVE: "IT.PROCUREMENT.APPROVE",
  IT_PROCUREMENT_REJECT: "IT.PROCUREMENT.REJECT",
  IT_PROCUREMENT_CREATE_PO: "IT.PROCUREMENT.CREATE_PO",
  IT_PROCUREMENT_APPROVE_PO: "IT.PROCUREMENT.APPROVE_PO",
  IT_PROCUREMENT_RECEIVE: "IT.PROCUREMENT.RECEIVE",
  IT_PROCUREMENT_EXPORT: "IT.PROCUREMENT.EXPORT",
  IT_PROCUREMENT_PRINT: "IT.PROCUREMENT.PRINT",

  IT_SUPPLIERS_VIEW: "IT.SUPPLIERS.VIEW",
  IT_SUPPLIERS_CREATE: "IT.SUPPLIERS.CREATE",
  IT_SUPPLIERS_UPDATE: "IT.SUPPLIERS.UPDATE",
  IT_SUPPLIERS_DELETE: "IT.SUPPLIERS.DELETE",

  IT_CURRENCY_VIEW: "IT.CURRENCY.VIEW",
  IT_CURRENCY_MANAGE: "IT.CURRENCY.MANAGE",
  IT_CURRENCY_UPDATE_RATES: "IT.CURRENCY.UPDATE_RATES",

  HR_DASHBOARD_VIEW: "HR.DASHBOARD.VIEW",

  HR_EMPLOYEES_VIEW: "HR.EMPLOYEES.VIEW",
  HR_EMPLOYEES_CREATE: "HR.EMPLOYEES.CREATE",
  HR_EMPLOYEES_UPDATE: "HR.EMPLOYEES.UPDATE",
  HR_EMPLOYEES_DELETE: "HR.EMPLOYEES.DELETE",
  HR_EMPLOYEES_ARCHIVE: "HR.EMPLOYEES.ARCHIVE",
  HR_EMPLOYEES_VIEW_SENSITIVE: "HR.EMPLOYEES.VIEW_SENSITIVE",
  HR_EMPLOYEES_VIEW_SALARY: "HR.EMPLOYEES.VIEW_SALARY",

  HR_DEPARTMENTS_VIEW: "HR.DEPARTMENTS.VIEW",
  HR_DEPARTMENTS_CREATE: "HR.DEPARTMENTS.CREATE",
  HR_DEPARTMENTS_UPDATE: "HR.DEPARTMENTS.UPDATE",
  HR_DEPARTMENTS_DELETE: "HR.DEPARTMENTS.DELETE",

  HR_POSITIONS_VIEW: "HR.POSITIONS.VIEW",
  HR_POSITIONS_CREATE: "HR.POSITIONS.CREATE",
  HR_POSITIONS_UPDATE: "HR.POSITIONS.UPDATE",
  HR_POSITIONS_DELETE: "HR.POSITIONS.DELETE",

  HR_ATTENDANCE_VIEW: "HR.ATTENDANCE.VIEW",
  HR_ATTENDANCE_CREATE: "HR.ATTENDANCE.CREATE",
  HR_ATTENDANCE_UPDATE: "HR.ATTENDANCE.UPDATE",
  HR_ATTENDANCE_APPROVE: "HR.ATTENDANCE.APPROVE",

  HR_LEAVE_VIEW: "HR.LEAVE.VIEW",
  HR_LEAVE_CREATE: "HR.LEAVE.CREATE",
  HR_LEAVE_UPDATE: "HR.LEAVE.UPDATE",
  HR_LEAVE_APPROVE: "HR.LEAVE.APPROVE",
  HR_LEAVE_REJECT: "HR.LEAVE.REJECT",

  HR_OVERTIME_VIEW: "HR.OVERTIME.VIEW",
  HR_OVERTIME_CREATE: "HR.OVERTIME.CREATE",
  HR_OVERTIME_APPROVE: "HR.OVERTIME.APPROVE",

  HR_TIMESHEETS_VIEW: "HR.TIMESHEETS.VIEW",
  HR_TIMESHEETS_CREATE: "HR.TIMESHEETS.CREATE",
  HR_TIMESHEETS_APPROVE: "HR.TIMESHEETS.APPROVE",

  HR_REQUESTS_VIEW: "HR.REQUESTS.VIEW",
  HR_REQUESTS_CREATE: "HR.REQUESTS.CREATE",
  HR_REQUESTS_UPDATE: "HR.REQUESTS.UPDATE",
  HR_REQUESTS_APPROVE: "HR.REQUESTS.APPROVE",
  HR_REQUESTS_REJECT: "HR.REQUESTS.REJECT",

  HR_DOCUMENTS_VIEW: "HR.DOCUMENTS.VIEW",
  HR_DOCUMENTS_CREATE: "HR.DOCUMENTS.CREATE",
  HR_DOCUMENTS_UPDATE: "HR.DOCUMENTS.UPDATE",
  HR_DOCUMENTS_DELETE: "HR.DOCUMENTS.DELETE",

  HR_CONTRACTS_VIEW: "HR.CONTRACTS.VIEW",
  HR_CONTRACTS_CREATE: "HR.CONTRACTS.CREATE",
  HR_CONTRACTS_UPDATE: "HR.CONTRACTS.UPDATE",
  HR_CONTRACTS_RENEW: "HR.CONTRACTS.RENEW",

  HR_BENEFITS_VIEW: "HR.BENEFITS.VIEW",
  HR_BENEFITS_CREATE: "HR.BENEFITS.CREATE",
  HR_BENEFITS_UPDATE: "HR.BENEFITS.UPDATE",

  HR_DEDUCTIONS_VIEW: "HR.DEDUCTIONS.VIEW",
  HR_DEDUCTIONS_CREATE: "HR.DEDUCTIONS.CREATE",
  HR_DEDUCTIONS_UPDATE: "HR.DEDUCTIONS.UPDATE",

  HR_COMPENSATION_VIEW: "HR.COMPENSATION.VIEW",
  HR_COMPENSATION_CREATE: "HR.COMPENSATION.CREATE",
  HR_COMPENSATION_UPDATE: "HR.COMPENSATION.UPDATE",

  HR_PAYROLL_VIEW: "HR.PAYROLL.VIEW",
  HR_PAYROLL_CREATE: "HR.PAYROLL.CREATE",
  HR_PAYROLL_UPDATE: "HR.PAYROLL.UPDATE",
  HR_PAYROLL_APPROVE: "HR.PAYROLL.APPROVE",

  HR_REPORTS_VIEW: "HR.REPORTS.VIEW",
  HR_REPORTS_EXPORT: "HR.REPORTS.EXPORT",
  HR_REPORTS_PRINT: "HR.REPORTS.PRINT",

  HR_SETTINGS_MANAGE: "HR.SETTINGS.MANAGE",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
