// Mirrors the rows seeded in supabase/migrations/20260101000010_seed_permissions.sql.
// Keeping these as named constants (rather than sprinkling raw strings
// through the app) means a typo becomes a compile error instead of a
// silently-denied action.
export const PERMISSIONS = {
  IT_TICKETS_VIEW: "IT.TICKETS.VIEW",
  IT_TICKETS_CREATE: "IT.TICKETS.CREATE",
  IT_TICKETS_UPDATE: "IT.TICKETS.UPDATE",
  IT_TICKETS_DELETE: "IT.TICKETS.DELETE",
  IT_TICKETS_ASSIGN: "IT.TICKETS.ASSIGN",
  IT_TICKETS_COMMENT: "IT.TICKETS.COMMENT",
  IT_TICKETS_RESOLVE: "IT.TICKETS.RESOLVE",
  IT_TICKETS_CLOSE: "IT.TICKETS.CLOSE",

  ADMIN_USERS_VIEW: "ADMIN.USERS.VIEW",
  ADMIN_USERS_MANAGE: "ADMIN.USERS.MANAGE",
  ADMIN_ROLES_MANAGE: "ADMIN.ROLES.MANAGE",
  ADMIN_DEPARTMENTS_MANAGE: "ADMIN.DEPARTMENTS.MANAGE",
  ADMIN_IT_CATEGORIES_MANAGE: "ADMIN.IT_CATEGORIES.MANAGE",
  ADMIN_COMPANY_SETTINGS_MANAGE: "ADMIN.COMPANY_SETTINGS.MANAGE",
  ADMIN_AUDIT_VIEW: "ADMIN.AUDIT.VIEW",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
