-- =========================================================================
-- SHARE PROCUREMENT ACROSS HR, FINANCE, ADMINISTRATION, AND PRODUCTION --
-- Part 2: permission keys. Mirrors the existing IT.PROCUREMENT.*/
-- IT.SUPPLIERS.* shape (20260101000040) exactly, one full set per
-- department. Grants happen in a later migration in this batch.
-- =========================================================================
insert into public.permissions (key, module_key, resource, action, description) values
  ('HR.PROCUREMENT.VIEW', 'HR', 'PROCUREMENT', 'VIEW', 'View HR procurement records'),
  ('HR.PROCUREMENT.CREATE', 'HR', 'PROCUREMENT', 'CREATE', 'Create HR purchase requests and quotations'),
  ('HR.PROCUREMENT.UPDATE', 'HR', 'PROCUREMENT', 'UPDATE', 'Edit HR procurement records'),
  ('HR.PROCUREMENT.DELETE', 'HR', 'PROCUREMENT', 'DELETE', 'Delete an HR purchase request'),
  ('HR.PROCUREMENT.SUBMIT', 'HR', 'PROCUREMENT', 'SUBMIT', 'Submit an HR purchase request for approval'),
  ('HR.PROCUREMENT.APPROVE', 'HR', 'PROCUREMENT', 'APPROVE', 'Approve or reject an HR purchase request'),
  ('HR.PROCUREMENT.REJECT', 'HR', 'PROCUREMENT', 'REJECT', 'Reject an HR purchase request'),
  ('HR.PROCUREMENT.CREATE_PO', 'HR', 'PROCUREMENT', 'CREATE_PO', 'Convert an approved HR request into a purchase order'),
  ('HR.PROCUREMENT.APPROVE_PO', 'HR', 'PROCUREMENT', 'APPROVE_PO', 'Approve an HR purchase order'),
  ('HR.PROCUREMENT.RECEIVE', 'HR', 'PROCUREMENT', 'RECEIVE', 'Record deliveries and receive HR purchase order items'),
  ('HR.PROCUREMENT.EXPORT', 'HR', 'PROCUREMENT', 'EXPORT', 'Export HR procurement data to CSV'),
  ('HR.PROCUREMENT.PRINT', 'HR', 'PROCUREMENT', 'PRINT', 'Print HR procurement documents'),
  ('HR.SUPPLIERS.VIEW', 'HR', 'SUPPLIERS', 'VIEW', 'View suppliers'),
  ('HR.SUPPLIERS.CREATE', 'HR', 'SUPPLIERS', 'CREATE', 'Create a supplier'),
  ('HR.SUPPLIERS.UPDATE', 'HR', 'SUPPLIERS', 'UPDATE', 'Edit a supplier'),
  ('HR.SUPPLIERS.DELETE', 'HR', 'SUPPLIERS', 'DELETE', 'Delete a supplier'),

  ('FINANCE.PROCUREMENT.VIEW', 'FINANCE', 'PROCUREMENT', 'VIEW', 'View Finance procurement records'),
  ('FINANCE.PROCUREMENT.CREATE', 'FINANCE', 'PROCUREMENT', 'CREATE', 'Create Finance purchase requests and quotations'),
  ('FINANCE.PROCUREMENT.UPDATE', 'FINANCE', 'PROCUREMENT', 'UPDATE', 'Edit Finance procurement records'),
  ('FINANCE.PROCUREMENT.DELETE', 'FINANCE', 'PROCUREMENT', 'DELETE', 'Delete a Finance purchase request'),
  ('FINANCE.PROCUREMENT.SUBMIT', 'FINANCE', 'PROCUREMENT', 'SUBMIT', 'Submit a Finance purchase request for approval'),
  ('FINANCE.PROCUREMENT.APPROVE', 'FINANCE', 'PROCUREMENT', 'APPROVE', 'Approve or reject a Finance purchase request'),
  ('FINANCE.PROCUREMENT.REJECT', 'FINANCE', 'PROCUREMENT', 'REJECT', 'Reject a Finance purchase request'),
  ('FINANCE.PROCUREMENT.CREATE_PO', 'FINANCE', 'PROCUREMENT', 'CREATE_PO', 'Convert an approved Finance request into a purchase order'),
  ('FINANCE.PROCUREMENT.APPROVE_PO', 'FINANCE', 'PROCUREMENT', 'APPROVE_PO', 'Approve a Finance purchase order'),
  ('FINANCE.PROCUREMENT.RECEIVE', 'FINANCE', 'PROCUREMENT', 'RECEIVE', 'Record deliveries and receive Finance purchase order items'),
  ('FINANCE.PROCUREMENT.EXPORT', 'FINANCE', 'PROCUREMENT', 'EXPORT', 'Export Finance procurement data to CSV'),
  ('FINANCE.PROCUREMENT.PRINT', 'FINANCE', 'PROCUREMENT', 'PRINT', 'Print Finance procurement documents'),
  ('FINANCE.SUPPLIERS.VIEW', 'FINANCE', 'SUPPLIERS', 'VIEW', 'View suppliers'),
  ('FINANCE.SUPPLIERS.CREATE', 'FINANCE', 'SUPPLIERS', 'CREATE', 'Create a supplier'),
  ('FINANCE.SUPPLIERS.UPDATE', 'FINANCE', 'SUPPLIERS', 'UPDATE', 'Edit a supplier'),
  ('FINANCE.SUPPLIERS.DELETE', 'FINANCE', 'SUPPLIERS', 'DELETE', 'Delete a supplier'),

  ('ADMIN.PROCUREMENT.VIEW', 'ADMIN', 'PROCUREMENT', 'VIEW', 'View Administration procurement records'),
  ('ADMIN.PROCUREMENT.CREATE', 'ADMIN', 'PROCUREMENT', 'CREATE', 'Create Administration purchase requests and quotations'),
  ('ADMIN.PROCUREMENT.UPDATE', 'ADMIN', 'PROCUREMENT', 'UPDATE', 'Edit Administration procurement records'),
  ('ADMIN.PROCUREMENT.DELETE', 'ADMIN', 'PROCUREMENT', 'DELETE', 'Delete an Administration purchase request'),
  ('ADMIN.PROCUREMENT.SUBMIT', 'ADMIN', 'PROCUREMENT', 'SUBMIT', 'Submit an Administration purchase request for approval'),
  ('ADMIN.PROCUREMENT.APPROVE', 'ADMIN', 'PROCUREMENT', 'APPROVE', 'Approve or reject an Administration purchase request'),
  ('ADMIN.PROCUREMENT.REJECT', 'ADMIN', 'PROCUREMENT', 'REJECT', 'Reject an Administration purchase request'),
  ('ADMIN.PROCUREMENT.CREATE_PO', 'ADMIN', 'PROCUREMENT', 'CREATE_PO', 'Convert an approved Administration request into a purchase order'),
  ('ADMIN.PROCUREMENT.APPROVE_PO', 'ADMIN', 'PROCUREMENT', 'APPROVE_PO', 'Approve an Administration purchase order'),
  ('ADMIN.PROCUREMENT.RECEIVE', 'ADMIN', 'PROCUREMENT', 'RECEIVE', 'Record deliveries and receive Administration purchase order items'),
  ('ADMIN.PROCUREMENT.EXPORT', 'ADMIN', 'PROCUREMENT', 'EXPORT', 'Export Administration procurement data to CSV'),
  ('ADMIN.PROCUREMENT.PRINT', 'ADMIN', 'PROCUREMENT', 'PRINT', 'Print Administration procurement documents'),
  ('ADMIN.SUPPLIERS.VIEW', 'ADMIN', 'SUPPLIERS', 'VIEW', 'View suppliers'),
  ('ADMIN.SUPPLIERS.CREATE', 'ADMIN', 'SUPPLIERS', 'CREATE', 'Create a supplier'),
  ('ADMIN.SUPPLIERS.UPDATE', 'ADMIN', 'SUPPLIERS', 'UPDATE', 'Edit a supplier'),
  ('ADMIN.SUPPLIERS.DELETE', 'ADMIN', 'SUPPLIERS', 'DELETE', 'Delete a supplier'),

  ('PRODUCTION.PROCUREMENT.VIEW', 'PRODUCTION', 'PROCUREMENT', 'VIEW', 'View Production procurement records'),
  ('PRODUCTION.PROCUREMENT.CREATE', 'PRODUCTION', 'PROCUREMENT', 'CREATE', 'Create Production purchase requests and quotations'),
  ('PRODUCTION.PROCUREMENT.UPDATE', 'PRODUCTION', 'PROCUREMENT', 'UPDATE', 'Edit Production procurement records'),
  ('PRODUCTION.PROCUREMENT.DELETE', 'PRODUCTION', 'PROCUREMENT', 'DELETE', 'Delete a Production purchase request'),
  ('PRODUCTION.PROCUREMENT.SUBMIT', 'PRODUCTION', 'PROCUREMENT', 'SUBMIT', 'Submit a Production purchase request for approval'),
  ('PRODUCTION.PROCUREMENT.APPROVE', 'PRODUCTION', 'PROCUREMENT', 'APPROVE', 'Approve or reject a Production purchase request'),
  ('PRODUCTION.PROCUREMENT.REJECT', 'PRODUCTION', 'PROCUREMENT', 'REJECT', 'Reject a Production purchase request'),
  ('PRODUCTION.PROCUREMENT.CREATE_PO', 'PRODUCTION', 'PROCUREMENT', 'CREATE_PO', 'Convert an approved Production request into a purchase order'),
  ('PRODUCTION.PROCUREMENT.APPROVE_PO', 'PRODUCTION', 'PROCUREMENT', 'APPROVE_PO', 'Approve a Production purchase order'),
  ('PRODUCTION.PROCUREMENT.RECEIVE', 'PRODUCTION', 'PROCUREMENT', 'RECEIVE', 'Record deliveries and receive Production purchase order items'),
  ('PRODUCTION.PROCUREMENT.EXPORT', 'PRODUCTION', 'PROCUREMENT', 'EXPORT', 'Export Production procurement data to CSV'),
  ('PRODUCTION.PROCUREMENT.PRINT', 'PRODUCTION', 'PROCUREMENT', 'PRINT', 'Print Production procurement documents'),
  ('PRODUCTION.SUPPLIERS.VIEW', 'PRODUCTION', 'SUPPLIERS', 'VIEW', 'View suppliers'),
  ('PRODUCTION.SUPPLIERS.CREATE', 'PRODUCTION', 'SUPPLIERS', 'CREATE', 'Create a supplier'),
  ('PRODUCTION.SUPPLIERS.UPDATE', 'PRODUCTION', 'SUPPLIERS', 'UPDATE', 'Edit a supplier'),
  ('PRODUCTION.SUPPLIERS.DELETE', 'PRODUCTION', 'SUPPLIERS', 'DELETE', 'Delete a supplier')
on conflict (key) do nothing;
